### ISSUE TITLE
[BUG] Too much MK3S<->MMU2 communication logging on serial port

### ISSUE THREAD

**Issue by thess** [prusa3d/Prusa-Firmware#4414]
**Printer type** - MK3S
**Printer firmware version** -  3.13.1+

**MMU upgrade** - MMU2S
**MMU upgrade firmware version** - 3.0.0, 3.0.1

**SD card or USB/Octoprint**
  Mainly USB/Octoprint

**Describe the bug**
 Serial communications between the printer and MMU are continually output on the USB port.
  
**To Reproduce**
  Connect to USB serial and notice continual chatter.
  
**Expected behavior**
 We need a way to suppress these messages from log output either by:
1. Providing menu option to disable (LogRequestMsg, LogResponse)
2. Conditional DEBUG build
3. Remove altogether
 
I suppose one could write an Octoprint serial filter to remove the transactions from the console but I would prefer not to have the excess data always clogging the serial communications path.

**Comment by gudnimg** [comment]
I agree with this. It would be nice to hide the Query (Q0) if nothing has changed since the last Q0. 

Q0 triggers every 1 second

**Comment by 3d-gussner** [comment]
@thess Nice to see you back on this repo. We have been discussing this few times and we gonna keep it for the moment.
Reason to keep it is to be able to check in the serial logs what happens BEFORE an error occurs. We don't have the resources to keep some lines in the buffer to read this buffer when an error is reported.
If you have an idea how we could ensure that we get access to the communication between MMU3 and printer please let us know.

Here my OctoPrint Filter for the Terminal output:
Settings -> Terminal Filter -> Name: `Suppress MMU` RegExp : `echo:MMU2`

Some parts of my `config.yaml`
```
....
feature:
  autoUppercaseBlacklist:
  - M117
  - M118
  - M707
  - M708
  - M850
  - D3
  
...


terminalFilters:
- name: Suppress temperature messages
  regex: '(Send: (N\d+\s+)?M105)|(Recv:\s+(ok\s+([PBN]\d+\s+)*)?([BCLPR]|T\d*):-?\d+)'
- name: Suppress SD status messages
  regex: '(Send: (N\d+\s+)?M27)|(Recv: SD printing byte)|(Recv: Not SD printing)'
- name: Suppress position messages
  regex: (Send:\s+(N\d+\s+)?M114)|(Recv:\s+(ok\s+)?X:[+-]?([0-9]*[.])?[0-9]+\s+Y:[+-]?([0-9]*[.])?[0-9]+\s+Z:[+-]?([0-9]*[.])?[0-9]+\s+E\d*:[+-]?([0-9]*[.])?[0-9]+).*
- name: Suppress wait responses
  regex: 'Recv: wait'
- name: Suppress processing responses
  regex: 'Recv: (echo:\s*)?busy:\s*processing'
- name: Suppress MMU
  regex: echo:MMU2
``` 

Changed `bug` label as it doesn't break things it is just annoying to `feature request` and `octoprint`

BTW: PrusLink/PrusaConnect and OctoPrint Plugins may/could use this serial logging to check the state/operations of the MMU3 :wink:
